### ISSUE TITLE
Fedora 23

### ISSUE THREAD

**Issue by armin-wies** [frans-fuerst/screensnippet#1]
`user@computer ~]$ ./byzanz-gui 
Traceback (most recent call last):
  File "/usr/local/src/byzanz-gui/byzanz-gui", line 8, in <module>
    from PyQt4 import QtGui, QtCore, uic
ImportError: No module named 'PyQt4'
`

`user@computer ~]$ sudo yum install python3-PyQt4`

**Comment by frans-fuerst** [comment]
Documentation added.
