### ISSUE TITLE
How to close the program?

### ISSUE THREAD

**Issue by armin-wies** [frans-fuerst/screensnippet#2]
I see that the software immediately plays back the recording in a loop. Thats's a nice feature.
Now I just wanna finish... I use the "x" from the playpack window decoration, which closes the playback window.

However, on the shell from which I run this, I'm still not back to my prompt.

When I press CTRL+c I see this:

```
^CTraceback (most recent call last):
  File "/home/straight21/bin/ssnippet", line 105, in <lambda>
    timer.timeout.connect(lambda: None)
KeyboardInterrupt

```

and every time I do so...
What is the intendet way to stop the program?

**Comment by frans-fuerst** [comment]
You would just close the UI main window. Qt is a bit special when it comes to signal handling. However I've made the UI shutdown correctly now when you press CTRL-C on command line.
